## Umgang mit Zeitwerten aus SPARQL

Siehe auch [https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior]

strftime steht für "String Format Time" und wandelt ein Datetime-Objekt in einen String.
strptime steht für "String Parse Time" und erstellt ein Datetime-Objekt aus einem String.

In [1]:
import pandas as pd
import numpy as np
flts = pd.read_csv('data/CRIDA-Regulations-Flights-20160401-20160430.csv',';')
flts.count()

LOBT                          152051
FlightUID                     152051
ADEP                          152051
ADES                          152051
EFTimeOfEntry                 152035
AFTimeOfEntry                 151918
AiracCycle                    152051
AircraftId                    152051
AircraftType                  152051
ATOT                          152011
CTOT                           25576
ETOT                          152011
IOBT                          152051
TaxiTime                      152011
ATA                           152016
CTA                            25576
ETA                           152017
mostPenalizingRegulationId     25600
mostPenalReguATO               23543
mostPenalReguEtO               25597
RegulationsCount              152051
ATFDelay                       25576
dtype: int64

In [2]:
rgflts = flts[pd.notnull(flts['CTOT'])]
nonrgflts = flts[pd.isnull(flts['CTOT'])]

In [9]:
rgflts.head(6)

,LOBT,FlightUID,ADEP,ADES,EFTimeOfEntry,AFTimeOfEntry,AiracCycle,AircraftId,AircraftType,ATOT,...,IOBT,TaxiTime,ATA,CTA,ETA,mostPenalizingRegulationId,mostPenalReguATO,mostPenalReguEtO,RegulationsCount,ATFDelay
1360,20160402 05:15:00,71596220160402,EGGW,LPFR,20160402 05:25:00,20160402 05:32:00,411,MON052,A320,20160402 05:32:00,...,20160402 05:15:00,10.0,20160402 08:07:10,20160402 08:08:46,20160402 08:08:46,RGA02,20160402 06:27:53,20160402 06:12:54,2,0.0
1361,20160402 05:12:00,71621120160402,ENCN,GCLP,20160402 05:17:00,20160402 05:25:17,411,SAS7487,B737,20160402 05:25:17,...,20160402 05:15:00,5.0,20160402 10:41:00,20160402 10:38:20,20160402 10:28:40,RGA02,20160402 07:26:34,20160402 07:20:20,3,9.0
1362,20160402 05:10:00,72265320160402,EGSS,GMMX,20160402 05:25:00,20160402 05:28:00,411,RYR78DJ,B738,20160402 05:28:00,...,20160402 05:10:00,15.0,20160402 08:50:39,20160402 08:49:57,20160402 08:49:57,RGA02,20160402 06:19:03,20160402 06:19:38,2,0.0
1363,20160402 05:10:00,72122820160402,EDDL,GCLP,20160402 05:23:00,20160402 05:33:21,411,SXD5BD,B738,20160402 05:33:21,...,20160402 05:10:00,13.0,20160402 10:10:42,20160402 10:02:42,20160402 09:55:38,RGA02,20160402 06:39:49,20160402 06:37:02,3,7.0
1364,20160402 05:06:00,71538820160402,LFPO,LPPT,20160402 05:16:00,20160402 05:33:00,411,VLG19QU,A320,20160402 05:33:00,...,20160402 05:06:00,10.0,20160402 07:41:28,20160402 07:42:33,20160402 07:24:08,RGA02,20160402 06:15:34,20160402 05:57:01,2,18.0
1365,20160402 05:05:00,71885320160402,LFPG,LPFR,20160402 05:21:00,20160402 05:18:00,411,EZY3951,A320,20160402 05:18:00,...,20160402 05:05:00,16.0,20160402 07:40:56,20160402 07:44:19,20160402 07:44:19,RGA02,20160402 06:03:16,20160402 06:07:05,3,0.0

In [18]:
from datetime import datetime

atot = datetime.strptime(rgflts.iloc[0]['ATOT'], '%Y%m%d %H:%M:%S')
iobt = datetime.strptime(rgflts.iloc[0]['IOBT'], '%Y%m%d %H:%M:%S')
diff = atot -iobt

print(rgflts.iloc[0]['FlightUID'])
print(rgflts.iloc[0]['ATOT'] + ' -->' + str(atot))
print(rgflts.iloc[0]['IOBT'] + ' -->' + str(iobt))
str(diff)

71596220160402
20160402 05:25:00 -->2016-04-02 05:32:00
20160402 05:15:00 -->2016-04-02 05:15:00

'0:17:00'

Das ganze kann man jetzt natürlich mit der kompletten Tabelle machen:

In [24]:
rgflts['diff'] = rgflts['ATA'].apply(lambda x: datetime.strptime(x, '%Y%m%d %H:%M:%S'))
rgflts['diff'] = rgflts['diff'] - rgflts['ETA'].apply(lambda y: datetime.strptime(y, '%Y%m%d %H:%M:%S'))



#datetime.strptime(rgflts['ATA'], '%Y%m%d %H:%M:%S') - datetime.strptime(rgflts['ETA'], '%Y%m%d %H:%M:%S') 


  
#df["geojson"] = df["geom"].apply(lambda x: json.dumps(wkt.loads(x)))
#df = df.drop('geom', 1)
rgflts.head(3)

/home/joerg/anaconda3/envs/datacron1/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/joerg/anaconda3/envs/datacron1/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,LOBT,FlightUID,ADEP,ADES,EFTimeOfEntry,AFTimeOfEntry,AiracCycle,AircraftId,AircraftType,ATOT,...,TaxiTime,ATA,CTA,ETA,mostPenalizingRegulationId,mostPenalReguATO,mostPenalReguEtO,RegulationsCount,ATFDelay,diff
1360,20160402 05:15:00,71596220160402,EGGW,LPFR,20160402 05:25:00,20160402 05:32:00,411,MON052,A320,20160402 05:32:00,...,10.0,20160402 08:07:10,20160402 08:08:46,20160402 08:08:46,RGA02,20160402 06:27:53,20160402 06:12:54,2,0.0,-1 days +23:58:24
1361,20160402 05:12:00,71621120160402,ENCN,GCLP,20160402 05:17:00,20160402 05:25:17,411,SAS7487,B737,20160402 05:25:17,...,5.0,20160402 10:41:00,20160402 10:38:20,20160402 10:28:40,RGA02,20160402 07:26:34,20160402 07:20:20,3,9.0,00:12:20
1362,20160402 05:10:00,72265320160402,EGSS,GMMX,20160402 05:25:00,20160402 05:28:00,411,RYR78DJ,B738,20160402 05:28:00,...,15.0,20160402 08:50:39,20160402 08:49:57,20160402 08:49:57,RGA02,20160402 06:19:03,20160402 06:19:38,2,0.0,00:00:42

In [19]:
rgflts['diff'] = rgflts['ATA'] - rgflts['ETA']
rgflts['diff'].mean()

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [1]:
import pandas as pd
from pandas.io.json import json_normalize, read_json
from SPARQLWrapper import SPARQLWrapper, JSON

def query_data(sparql_query, sparql_service_url='http://83.212.239.107:8890/sparql'):
    """
    Query the endpoint with the given query string and return the results as a pandas Dataframe.
    """
    # create the connection to the endpoint; set return format; ask for result
    sparql = SPARQLWrapper(sparql_service_url)  
    sparql.setQuery(sparql_query)
    sparql.setReturnFormat(JSON)
    result = sparql.query().convert()
    
    #clean up the column mess (thanks to David Knodt)
    for row in result['results']['bindings']:
        for key in row.keys():
            row[key] = row[key]['value']            
    if len(result["results"]["bindings"]):
        #return json_normalize(result["results"]["bindings"])
        #return read_json(str(result["results"]["bindings"]), orient = 'records' )
        dftemp = pd.DataFrame(result["results"]["bindings"])   #Problem: Pandas DataFrame() method sorted cols alphabetically
        dftemp = dftemp[result['head']['vars']]                #Solution: this reorders colmns like they were returned from SPARQL
        return dftemp
    else:
        return pd.DataFrame(columns=(result['head']['vars']))

In [2]:
def query_value_cleaning(df):
    """
    Drop URI prefixes from result values. Excpects a Pandas DataFrame as parameter.
    """
    if type(df) != pd.core.frame.DataFrame:
        print('Query Cleaning nicht möglich - es wurde kein Pandas DataFrame übergeben.')
        print ('der Typ des Objekts ist ein {}'.format(type(df)) )
        return df
    
    prefixes = ['http://www.datacron-project.eu/datAcron#']
    prefixes.append('http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#')
    prefixes.append('http://www.w3.org/2001/XMLSchema#')
    prefixes.append('http://www.w3.org/2000/01/rdf-schema#')
    prefixes.append('java:datAcronTester.unipi.gr.sparql_functions.')
    prefixes.append('http://www.w3.org/1999/02/22-rdf-syntax-ns#')
    prefixes.append('http://www.openlinksw.com/schemas/virtrdf#')
    
    for item in prefixes:
        for column in df:
            df[column].replace(regex=True, inplace=True, to_replace=item, value='')
    return df

In [3]:
def regexify(df, column):
    """
    Creates a REGEX expression which matches the values of a pd.DataFrame column OR-wise.
    E.g. the pattern matches if the search string contains one or more elements of the column.
    """
    regex = '('
    for i in range (len(df)):
        regex = regex + df.iloc[i][column] + '|'
    
    regex = regex[:-3] + ')'
    return regex

In [54]:
def wkt_to_geojson(dataframe, wkt_column_name, geojson_column_name):
    if type(dataframe) != pd.core.frame.DataFrame:
        raise TypeError('The parameter dataframe must be a Pandas DataFrame.')
    if not wkt_column_name in dataframe.columns:
        raise ValueError('No column with the specified name found in the DataFrame')
    dataframe[geojson_column_name] = dataframe[wkt_column_name].apply(lambda x: wkt.loads(x))
    return dataframe

def extract_coordinates(geojson):
    return geojson['coordinates']

def geojson_to_coord_only(dataframe, geojson_column, coord_column):
    dataframe[coord_column] =  dataframe[geojson_column].apply(lambda x: extract_coordinates(x))
    return dataframe

def geojsonify(dataframe, time_column, coord_column):
    res = {}
    res['type'] = 'LineString'
    res['coordinates'] = []
    res['properties'] = {'times': []}

    for x in range(len(dataframe)):
        res['coordinates'].append(dataframe.iloc[x][coord_column])
        res['properties']['times'].append(dataframe.iloc[x][time_column])
    res2 = {}
    res2['type']  = 'Feature'
    res2['geometry'] = res
    return res2

In [55]:
sparql_query = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT DISTINCT * WHERE {
  ?flight_plan_ID a :FM_RTFM ;
                    :departureAirport ?dep ;
                    :destinationAirport ?dest ;
                    :reportsTrajectory ?trajectory_ID .
  ?trajectory_ID dul:hasConstituent/:hasWKT ?geom

} LIMIT 100

"""

#to query another endpoint, change the URL for the service and the query
df = query_data(sparql_query)
query_value_cleaning(df)
df.to_csv("data/trajectories.csv")
df.head(20)

from geomet import wkt
import json

#Convert WKT column into a gejson column
df["geojson"] = df["geom"].apply(lambda x: json.dumps(wkt.loads(x)))
df = df.drop('geom', 1)

df.head(20)

,flight_plan_ID,dep,dest,trajectory_ID,geojson
0,flight_plan_AA51114077,Place_MontpellierMediterranee_Airport,Place_BastiaPoretta_Airport,traj_AA51114077_20160401003000,"{""type"": ""LineString"", ""coordinates"": [[3.9613..."
1,flight_plan_AA51114336,Place_Bristol___Lulsgate,Place_TenerifeSur_ReinaSofia_Airport,traj_AA51114336_20160331154500,"{""type"": ""LineString"", ""coordinates"": [[-2.719..."
2,flight_plan_AA51114524,Place_Valencia_Manises_Airport,Place_Bucuresti_HenriCoanda_Airport,traj_AA51114524_20160331183000,"{""type"": ""LineString"", ""coordinates"": [[-0.481..."
3,flight_plan_AA51115368,Place_Nantes_Atlantique_Airport,Place_London___Gatwick_Airport,traj_AA51115368_20160331155000,"{""type"": ""LineString"", ""coordinates"": [[-1.607..."
4,flight_plan_AA51121974,Place_QuimperPluguffan_Airport,Place_ParisOrly_Airport,traj_AA51121974_20160401044000,"{""type"": ""LineString"", ""coordinates"": [[-4.167..."
5,flight_plan_AA51125894,Place_Valencia_Manises_Airport,Place_Lisboa___Portela,traj_AA51125894_20160401045000,"{""type"": ""LineString"", ""coordinates"": [[-0.481..."
6,flight_plan_AA51134032,Place_ParisOrly_Airport,Place_Lisboa___Portela,traj_AA51134032_20160401043000,"{""type"": ""LineString"", ""coordinates"": [[2.3794..."
7,flight_plan_AA51134247,Place_Barcelona_ElPrat_Airport,Place_Lisboa___Portela,traj_AA51134247_20160401044000,"{""type"": ""LineString"", ""coordinates"": [[2.0783..."
8,flight_plan_AA51137475,Place_Erzurum_Airport,Place_Istanbul_SabihaGokcen_Airport,traj_AA51137475_20160401053000,"{""type"": ""LineString"", ""coordinates"": [[41.170..."
9,flight_plan_AA51138917,Place_Praha_Ruzyne_Airport,Place_FrankfurtMain_Airport,traj_AA51138917_20160401052000,"{""type"": ""LineString"", ""coordinates"": [[14.26,..."
10,flight_plan_AA51139876,Place_Casablanca_MohammedV_Airport,Place_Barcelona_ElPrat_Airport,traj_AA51139876_20160401074000,"{""type"": ""LineString"", ""coordinates"": [[-7.581..."
11,flight_plan_AA51139876,Place_Casablanca_MohammedV_Airport,Place_Barcelona_ElPrat_Airport,traj_AA51139876_20160401074000,"{""type"": ""LineString"", ""coordinates"": [[-7.581..."
12,flight_plan_AA51139907,Place_Koebenhavn_Kastrup_Airport,Place_ParisCharlesDeGaulle_Airport,traj_AA51139907_20160401045000,"{""type"": ""LineString"", ""coordinates"": [[12.656..."
13,flight_plan_AA51140568,Place_Gaziantep_Airport,Place_Istanbul_Ataturk_Airport,traj_AA51140568_20160401043500,"{""type"": ""LineString"", ""coordinates"": [[37.478..."
14,flight_plan_AA51145028,Place_Katowice_Pyrzowice_Airport,Place_Luton_Airport,traj_AA51145028_20160401162500,"{""type"": ""LineString"", ""coordinates"": [[19.08,..."
15,flight_plan_AA51145034,Place_Roma_Fiumicino_Airport,Place_Istanbul_Ataturk_Airport,traj_AA51145034_20160401051000,"{""type"": ""LineString"", ""coordinates"": [[12.238..."
16,flight_plan_AA51145052,Place_Roma_Fiumicino_Airport,Place_Geneve_Airport,traj_AA51145052_20160401143000,"{""type"": ""LineString"", ""coordinates"": [[12.238..."
17,flight_plan_AA51145083,Place_Faro_Airport,Place_Bristol___Lulsgate,traj_AA51145083_20160401063000,"{""type"": ""LineString"", ""coordinates"": [[-7.965..."
18,flight_plan_AA51145084,Place_LyonSaintExupery_Airport,Place_ParisCharlesDeGaulle_Airport,traj_AA51145084_20160401092500,"{""type"": ""LineString"", ""coordinates"": [[5.0811..."
19,flight_plan_AA51145295,Place_London___Gatwick_Airport,Place_Malaga_CostaDelSol_Airport,traj_AA51145295_20160401144000,"{""type"": ""LineString"", ""coordinates"": [[-0.190..."

# Trajektorien aus einzelnen Nodes zusammenbauen

Beginnen wir mit der Beispielabfrage (Seite 4 bottom):

In [65]:
sparql_query = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT ?node ?time ?position 
WHERE {
   :traj_AA51114077_20160401003000 :hasPart ?node .
   ?node dul:hasConstituent/:TimeStart ?time ;
         dul:hasConstituent/:hasWKT ?position  ;
         ?p ?o
} ORDER BY ?time

"""

#traj_AA51114077_20160401003000
#traj_AA51114077_20160401003000_m1  <---- according tutorial, we should use, but gives 0 results

traj = query_data(sparql_query)
query_value_cleaning(traj)

traj.head(50)

,node,time,position
0,n_AA51114077_20160401003000_1,2016-04-01T03:52:30,POINT(3.961389 43.583333)
1,n_AA51114077_20160401003000_1,2016-04-01T03:52:30,POINT(3.961389 43.583333)
2,n_AA51114077_20160401003000_1,2016-04-01T03:52:30,POINT(3.961389 43.583333)
3,n_AA51114077_20160401003000_1,2016-04-01T03:52:30,POINT(3.961389 43.583333)
4,n_AA51114077_20160401003000_1,2016-04-01T03:52:30,POINT(3.961389 43.583333)
5,n_AA51114077_20160401003000_1,2016-04-01T03:52:30,POINT(3.961389 43.583333)
6,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(8.626944 43.118333)
7,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(8.626944 43.118333)
8,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.506944 42.661944)
9,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.506944 42.661944)
10,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(3.968056 43.580833)
11,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(3.968056 43.580833)
12,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.917222 43.34)
13,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.917222 43.34)
14,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(3.986389 43.575278)
15,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(3.986389 43.575278)
16,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(3.998333 43.5725)
17,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(3.998333 43.5725)
18,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.163333 43.530556)
19,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.163333 43.530556)
20,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.269167 43.503889)
21,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.269167 43.503889)
22,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.398889 43.471111)
23,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.398889 43.471111)
24,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.540278 43.435278)
25,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.540278 43.435278)
26,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.716944 43.390556)
27,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.716944 43.390556)
28,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(5.159722 43.276667)
29,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(5.159722 43.276667)
30,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(5.729722 43.229167)
31,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(5.729722 43.229167)
32,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(8.303056 43.170833)
33,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(8.303056 43.170833)
34,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(8.759167 43.099722)
35,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(8.759167 43.099722)
36,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.059444 43.057222)
37,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.059444 43.057222)
38,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.395556 42.978333)
39,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.395556 42.978333)
40,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.488333 42.955833)
41,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.488333 42.955833)
42,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.513333 42.679444)
43,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.513333 42.679444)
44,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.526111 42.714722)
45,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.526111 42.714722)
46,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.542222 42.758889)
47,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.542222 42.758889)
48,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.568056 42.829444)
49,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.568056 42.829444)

In [61]:
sparql_query = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT ?node ?time ?position 
WHERE {
   :traj_AA51114077_20160401003000_m1 :hasPart ?node .
   ?node dul:hasConstituent/:TimeStart ?time ;
         dul:hasConstituent/:hasWKT ?position  ;
         ?p ?o
} ORDER BY ?time

"""

#traj_AA51114077_20160401003000
#traj_AA51114077_20160401003000_m1  <---- according tutorial, we should use, but gives 0 results

traj = query_data(sparql_query)
query_value_cleaning(traj)
traj.to_csv("data/node.csv")

traj = traj.drop_duplicates(subset = 'node', keep = 'first')

traj = traj.sort_values('node')
traj.to_csv("data/trajectory_drop_duplicates.csv")
traj = wkt_to_geojson(traj, 'position', 'geojson')
traj = geojson_to_coord_only(traj, 'geojson', 'coord_only')

traj.head(5)

,node,time,position,geojson,coord_only
2764,n_AA51145083_20160401063000_1,2016-04-01T06:49:16,POINT(-7.965833 37.014444),"{'type': 'Point', 'coordinates': [-7.965833, 3...","[-7.965833, 37.014444]"
2788,n_AA51145083_20160401063000_10,2016-04-01T06:59:13,POINT(-7.95 37.597222),"{'type': 'Point', 'coordinates': [-7.95, 37.59...","[-7.95, 37.597222]"
1184,n_AA51145083_20160401063000_11,2016-04-01T06:59:34,POINT(-3.443889 50.693333),"{'type': 'Point', 'coordinates': [-3.443889, 5...","[-3.443889, 50.693333]"
1258,n_AA51145083_20160401063000_12,2016-04-01T07:00:57,POINT(-3.443889 50.693333),"{'type': 'Point', 'coordinates': [-3.443889, 5...","[-3.443889, 50.693333]"
74,n_AA51145083_20160401063000_13,2016-04-01T07:02:33,POINT(-3.443889 50.693333),"{'type': 'Point', 'coordinates': [-3.443889, 5...","[-3.443889, 50.693333]"

In [62]:
from folium.plugins import TimestampedGeoJson

geojs = geojsonify(traj, 'time', 'coord_only')

map2 = folium.Map(location=[40,10], zoom_start=4, control_scale=True, prefer_canvas=True)
#tgj = TimestampedGeoJson(data = ng2, period = 'PT1M')
#map2.add_child(tgj, name='sometimestampedgeojson')


c = folium.GeoJson(geojs, name = 'Traj with time',overlay=True, 
                       style_function = lambda feature: {'fillColor': '#ffaf00','color': 'blue', 'weight': 2.5,'dashArray': '5, 5'},
                       highlight_function = lambda feature: {'fillColor': '#ffaf00','color': 'green', 'weight': 5,'dashArray': '5, 5'})
c.add_child(folium.Popup('some popup'))
c.add_to(map2)
folium.LayerControl().add_to(map2)
map2.save(outfile='maps/map2.html')

map2